name: "Build - Dev Android Mobile App"
on:
  push:
    branches: [ "dev" ]
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
       
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Ionic
        run: cd dev-sec-ops && npm install -g @ionic/cli

      - name: Install npm dependencies
        run: cd dev-sec-ops && npm install --force
      
      - name: Build Ionic Web assets
        run: cd dev-sec-ops && ionic build

      - name: Sync Ionic Web assets
        run: cd dev-sec-ops && npx cap sync android

      # - name: Move Certificates
      #   run: mkdir -p android/capacitor-cordova-android-plugins/src/main/assets/www/ && cp -r android/app/src/main/assets/public/certificates android/capacitor-cordova-android-plugins/src/main/assets/www/certificates
      
      # - name: Increment Version
      #   run: cd dev-sec-ops && npm run cap:config

      - name: Create release build
        run: cd dev-sec-ops && cd android && ./gradlew assembleRelease && cd ..
            
      - name: Zipalign & Sign apk
        uses: r0adkll/sign-android-release@v1
        # with:
        #   releaseDirectory: android/app/build/outputs/apk/release
        #   signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
        #   alias: ${{ secrets.ANDROID_ALIAS }}
        #   keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: dev-sec-ops/android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
      
      - run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$REPO_NAME/$REPO_NAME
          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME/$REPO_NAME
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          
      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.1
        env:
          INPUT_FILE_NAME: dev-sec-ops/android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
          