name: "Build - Dev Android Mobile App"
on:
  push:
    branches: [ "dev" ]
jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Install ESLint
        run: |
          npm install eslint@8.10.0

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format html
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      # - name: Checkout source
      #   uses: actions/checkout@v2

      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v2

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v2


      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
          
      # - name: Set up Java
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: "temurin"
      #     java-version: 17

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x

      # - name: Install Ionic
      #   run: npm install -g @ionic/cli

      # - name: Install npm dependencies
      #   run: npm install --force
      
      # - name: Build Ionic Web assets
      #   run: ionic build

      # - name: Sync Ionic Web assets
      #   run: npx cap sync android

      # - name: Move Certificates
      #   run: mkdir -p android/capacitor-cordova-android-plugins/src/main/assets/www/ && cp -r android/app/src/main/assets/public/certificates android/capacitor-cordova-android-plugins/src/main/assets/www/certificates
      
      # - name: Increment Version
      #   run: npm run cap:config

      # - name: Create release build
      #   run: cd android && ./gradlew assembleRelease && cd ..
            
      # - name: Zipalign & Sign apk
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: android/app/build/outputs/apk/release
      #     signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }} 
      #     alias: ${{ secrets.ANDROID_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      # - name: Upload dev APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: android-build
      #     # path: android/app/build/outputs/apk/release/app-release-unsigned.apk
      #     path: android/app-release-unsigned.apk
      
      # - name: Fix Permissions for MobSF Docker
      #   run: |
      #     set -e
      #     sudo mkdir -p /home/runner/work/_temp/_github_home
      #     sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

      #     sudo mkdir -p /home/runner/work/$REPO_NAME/$REPO_NAME
      #     sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME/$REPO_NAME
      #   env:
      #     REPO_NAME: ${{ github.event.repository.name }}\

      # - name: Set-up Java
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: '12.x'  

      # - name: Run MobSF Analysis
      #   uses: fundacaocerti/mobsf-action@v1.7.1
      #   env:
      #     # INPUT_FILE_NAME: android/app/build/outputs/apk/release/app-release-unsigned.apk
      #     INPUT_FILE_NAME: android/app-release-unsigned.apk
      #     SCAN_TYPE: apk
      #     OUTPUT_FILE_NAME: mobsf-report
      #   run:
      #     JAVA_DIRECTORY



      # - name: Cleanup MobSF Permissions
      #   run: |
      #     set -e
      #     sudo chown -R runner:docker /home/runner/work/_temp/_github_home
      #     sudo chown -R runner:docker /home/runner/work/$REPO_NAME/$REPO_NAME
      #   env:
      #     REPO_NAME: ${{ github.event.repository.name }}

      # - name: Upload MobSF Analysis PDF Result
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mobsf-report.pdf
      #     path: mobsf-report.pdf

      # - name: Upload MobSF Analysis JSON Result
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mobsf-report.json
      #     path: mobsf-report.json
          